### PR TITLE
Remove unused package

### PR DESCRIPTION
**Pull request by vanthao03596**
I want to use this package standalone but it install yajra/laravel-datatables-buttons too.

### CODE REVIEW

**Comment by yajra** [comment]
I think the buttons can be removed, but the validation is actually needed to validate the request.

**Comment by yajra** [comment]
Can you please share some snippets on how to use this as standalone? Haven't tried it yet. Thanks!

**Comment by vanthao03596** [comment]
@yajra  I mean use yajra/laravel-datatables-oracle with yajra-laravel-datatables-editor. Don't use html builder just write javascript code

**Comment by vanthao03596** [comment]
thank's @yajra everything work pretty sweet. One more thing, how i can use editor with tinymce or ckeditor ?
ezgif com-gif-maker

**Pull request merged**
